language: python
python:
  - "3.4"
cache: pip
install:
  - pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.1-cp34-cp34m-linux_x86_64.whl
script:
  - python -m unittest
