#!/bin/bash --login
#PBS -N tensor
#PBS -A d122
#PBS -l select=1
#PBS -l walltime=00:20:00

export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
#export PYTHONPATH="$PBS_O_WORKDIR/venv/lib/python"
cd $PBS_O_WORKDIR

module swap PrgEnv-cray PrgEnv-gnu

#module load python-compute/3.4.3
#module load pc-mpi4py/2.0.0-python3

source archer_venv/bin/activate

aprun -n 2  trainer2/main.py --server_protocol=grpc+mpi
