trainingInput:
  scaleTier: CUSTOM
  masterType: standard_gpu
  workerType: standard_gpu
  parameterServerType: standard
  workerCount: 3
  parameterServerCount: 1
  region: us-east1
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: total_loss
    maxTrials: 6
    params:
    - parameter_name: weight_decay
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.001
      scaleType: UNIT_LOG_SCALE
    - parameter_name: learning_rate_decay_factor
      type: DOUBLE
      minValue: 0.95
      maxValue: 0.99
      scaleType: UNIT_LOG_SCALE
#    - parameter_name: momentum
#      type: DOUBLE
#      minValue: 0.85
#      maxValue: 0.95
#      scaleType: UNIT_LOG_SCALE
    - parameter_name: num_epochs_per_decay
      type: DOUBLE
      minValue: 0.0
      maxValue: 1.0
      scaleType: UNIT_LINEAR_SCALE
#    - parameter_name: batch_size
#      type: INTEGER
#      minValue: 32
#      maxValue: 512
#      scaleType: UNIT_LINEAR_SCALE
#    - parameterName: num_epochs_per_decay
#      type: INTEGER
#      minValue: 0
#      maxValue: 15
#      scaleType: UNIT_LINEAR_SCALE
#    - parameterName: learning_rate
#      type: DOUBLE
#      minValue: 0.0001
#      maxValue: 0.01
#      scaleType: UNIT_LOG_SCALE
#    - parameterName: epsilon
#      type: DOUBLE
#      minValue: 0.001
#      maxValue: 1.0
#      scaleType: UNIT_LOG_SCALE
