trainingInput:
  scaleTier: CUSTOM
  masterType: standard_gpu
  workerType: standard_gpu
  parameterServerType: standard
  workerCount: 0
  parameterServerCount: 0
  region: us-east1
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: total_loss
    maxTrials: 6
    params:
    - parameterName: learning_rate
      type: DOUBLE
      minValue: 0.001
      maxValue: 0.01
      scaleType: UNIT_LOG_SCALE
#    - parameterName: optimizer
#      type: CATEGORICAL
#      categoricalValues: ['momentum', 'adam']
    - parameterName: activation
      type: CATEGORICAL
      categoricalValues: ['relu', 'elu']
